"""Core: discovery, parsing, glob matching, and per-session injection state.

No Hermes imports at module level (defensive, read-only import of the session-cwd
resolver only, with an os.getcwd() fallback) so this package is testable standalone.
"""

from __future__ import annotations

import os
import re
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:  # optional; the fallback parser covers plain frontmatter
    import yaml  # type: ignore
except Exception:  # pragma: no cover - PyYAML is usually present in Hermes
    yaml = None  # type: ignore

GENERATED_MARKER = "<!-- generated by hermes context-rules"

# Absolute cap for a rule body injected into a tool result (chars).
DEFAULT_MAX_INJECT = 32_000
# Absolute cap for the system-prompt section (the host caps sections at 4_000).
MAX_PROMPT_SECTION_CHARS = 3_900
# Cap for one always-rule body inside the prompt section.
MAX_ALWAYS_BODY_CHARS = 1_200

MODE_ALWAYS = "always"
MODE_GLOB = "glob"
MODE_DESC = "desc"
MODE_MANUAL = "manual"

_STATE_LOCK = threading.Lock()
# session_id -> rule_key -> True once the full body has been injected.
_INJECTED: Dict[str, Dict[str, bool]] = {}
# root dir string -> (fingerprint, [Rule]) cache; fingerprint = tuple((path, mtime_ns)).
_RULES_CACHE: Dict[str, Tuple[Tuple[Tuple[str, int], ...], List["Rule"]]] = {}
_GLOB_CACHE: Dict[str, re.Pattern] = {}


# --------------------------------------------------------------------------
# session cwd


def session_cwd(explicit: Optional[str] = None) -> Path:
    """Best-effort session working directory."""
    if explicit:
        return Path(explicit).expanduser().resolve()
    try:  # read-only use of the host resolver; not part of the plugin contract
        from agent.runtime_cwd import resolve_context_cwd  # type: ignore

        resolved = resolve_context_cwd()
        if resolved:
            return Path(str(resolved)).resolve()
    except Exception:
        pass
    return Path.cwd().resolve()


# --------------------------------------------------------------------------
# frontmatter parsing


def _fallback_yaml(text: str) -> Dict[str, Any]:
    """Parse the flat ``key: value`` / ``- item`` / ``[a, b]`` subset we need."""
    data: Dict[str, Any] = {}
    current_list_key: Optional[str] = None
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and current_list_key:
            item = _unquote(stripped[2:].strip())
            values = data.setdefault(current_list_key, [])
            if isinstance(values, list):
                values.append(item)
            continue
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        current_list_key = None
        if not value:
            data[key] = None
            continue
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[key] = [_unquote(v) for v in _split_flow_items(inner)] if inner else []
            continue
        if value in ("true", "True"):
            data[key] = True
        elif value in ("false", "False"):
            data[key] = False
        else:
            data[key] = _unquote(value)
            if re.fullmatch(r"[\w./?*\[\]-]+", str(data[key])) is None and not value.startswith(("'", '"')):
                current_list_key = None
            if not value.startswith(("'", '"')) and "\n" in value:
                data[key] = value
            # a bare value that looks like a list header ("globs:" then "- x" lines)
            current_list_key = key
    return data


_DQ_ESCAPES = {'"': '"', "\\": "\\", "/": "/", "n": "\n", "t": "\t",
               "r": "\r", "b": "\b", "f": "\f", "0": "\0"}


def _decode_dq(inner: str) -> str:
    """Decode YAML double-quoted escapes (the json.dumps subset we write)."""
    out: List[str] = []
    i = 0
    while i < len(inner):
        ch = inner[i]
        if ch == "\\" and i + 1 < len(inner):
            nxt = inner[i + 1]
            if nxt == "u" and i + 6 <= len(inner):
                try:
                    out.append(chr(int(inner[i + 2 : i + 6], 16)))
                    i += 6
                    continue
                except ValueError:
                    pass
            out.append(_DQ_ESCAPES.get(nxt, nxt))
            i += 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def _split_flow_items(inner: str) -> List[str]:
    """Split a flow-sequence body on commas that are not inside quotes."""
    items: List[str] = []
    buf: List[str] = []
    quote: Optional[str] = None
    for ch in inner:
        if quote is not None:
            buf.append(ch)
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
            buf.append(ch)
        elif ch == ",":
            items.append("".join(buf).strip())
            buf = []
        else:
            buf.append(ch)
    tail = "".join(buf).strip()
    if tail or items:
        items.append(tail)
    return [it for it in items if it]


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        inner = value[1:-1]
        if value[0] == '"':
            return _decode_dq(inner)
        return inner.replace("''", "'")
    return value


def _parse_frontmatter(text: str) -> Tuple[Dict[str, Any], str]:
    """Split ``---`` frontmatter; return (metadata dict, body)."""
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm_text = "\n".join(lines[1:i])
            body = "\n".join(lines[i + 1 :]).lstrip("\n")
            data: Dict[str, Any] = {}
            if fm_text.strip():
                if yaml is not None:
                    try:
                        loaded = yaml.safe_load(fm_text)
                        if isinstance(loaded, dict):
                            data = loaded
                    except Exception:
                        data = {}
                if not data:
                    data = _fallback_yaml(fm_text)
            return data, body
    return {}, text


def _as_glob_list(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, str):
        parts = [p.strip() for p in value.split(",")]
        return [p for p in parts if p]
    if isinstance(value, (list, tuple)):
        return [str(p).strip() for p in value if str(p).strip()]
    return []


# --------------------------------------------------------------------------
# rule model


@dataclass
class Rule:
    name: str
    root: Path  # project dir containing the rules directory
    path: Path  # the rule file itself
    source: str  # "cursor" | "claude"
    mode: str  # always | glob | desc | manual
    globs: List[str] = field(default_factory=list)
    description: str = ""
    enforce: str = ""
    body: str = ""

    @property
    def key(self) -> str:
        return f"{self.root}|{self.source}|{self.name}"

    @property
    def relpath(self) -> str:
        try:
            return self.path.relative_to(self.root).as_posix()
        except ValueError:
            return self.path.as_posix()


def _resolve_mode(meta: Dict[str, Any], source: str) -> str:
    if source == "claude" and not meta:
        # Claude Code loads .claude/rules/*.md unconditionally.
        return MODE_ALWAYS
    if meta.get("alwaysApply") is True:
        return MODE_ALWAYS
    if _as_glob_list(meta.get("globs")):
        return MODE_GLOB
    if str(meta.get("description") or "").strip():
        return MODE_DESC
    return MODE_MANUAL


def _parse_rule_file(path: Path, root: Path, source: str) -> Optional[Rule]:
    try:
        text = path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return None
    if GENERATED_MARKER in text.splitlines()[0] if text else False:
        return None  # our own /context-rules sync output
    if GENERATED_MARKER in text[:400]:
        return None
    meta, body = _parse_frontmatter(text)
    if not body.strip() and not meta:
        return None
    enforce = str(meta.get("enforce") or "").strip()
    if enforce and not _as_glob_list(meta.get("globs")):
        # An enforce gate needs a file scope; without globs it can never fire.
        meta = dict(meta)
        meta.setdefault("globs", ["**/*"])
    return Rule(
        name=path.stem,
        root=root,
        path=path,
        source=source,
        mode=_resolve_mode(meta, source),
        globs=_as_glob_list(meta.get("globs")),
        description=str(meta.get("description") or "").strip(),
        enforce=enforce,
        body=body.strip(),
    )


# --------------------------------------------------------------------------
# discovery


def _git_root(start: Path) -> Optional[Path]:
    for parent in [start, *start.parents]:
        if (parent / ".git").exists():
            return parent
    return None


def find_rule_roots(cwd: Path) -> List[Path]:
    """Directories from cwd up to the git root that carry a rules directory."""
    start = cwd.expanduser().resolve()
    top = _git_root(start)
    chain: List[Path] = []
    node = start
    while True:
        chain.append(node)
        if node == top or node == node.parent:
            break
        node = node.parent
    roots = [d for d in chain if (d / ".cursor" / "rules").is_dir() or (d / ".claude" / "rules").is_dir()]
    return roots


def _fingerprint(root: Path) -> Tuple[Tuple[str, int], ...]:
    entries: List[Tuple[str, int]] = []
    for sub, pattern in ((".cursor/rules", "*.mdc"), (".cursor/rules", "*.md"), (".claude/rules", "*.md")):
        rules_dir = root / sub
        if not rules_dir.is_dir():
            continue
        try:
            for f in sorted(rules_dir.glob(pattern)):
                try:
                    entries.append((str(f), f.stat().st_mtime_ns))
                except OSError:
                    continue
        except OSError:
            continue
    return tuple(entries)


def load_rules(cwd: Optional[Path] = None, explicit_cwd: Optional[str] = None) -> List[Rule]:
    """All rules for the session cwd, in discovery order (.cursor before .claude per root)."""
    base = cwd if cwd is not None else session_cwd(explicit_cwd)
    rules: List[Rule] = []
    for root in find_rule_roots(base):
        with _STATE_LOCK:
            cached = _RULES_CACHE.get(str(root))
        fp = _fingerprint(root)
        if cached and cached[0] == fp:
            rules.extend(cached[1])
            continue
        fresh: List[Rule] = []
        for sub, pattern, source in (
            (".cursor/rules", "*.mdc", "cursor"),
            (".cursor/rules", "*.md", "cursor"),
            (".claude/rules", "*.md", "claude"),
        ):
            rules_dir = root / sub
            if not rules_dir.is_dir():
                continue
            for f in sorted(rules_dir.glob(pattern)):
                rule = _parse_rule_file(f, root, source)
                if rule is not None:
                    fresh.append(rule)
        with _STATE_LOCK:
            _RULES_CACHE[str(root)] = (fp, fresh)
        rules.extend(fresh)
    return rules


# --------------------------------------------------------------------------
# glob matching


def _translate_glob(pat: str) -> str:
    out: List[str] = []
    i, n = 0, len(pat)
    while i < n:
        c = pat[i]
        if c == "*":
            j = i
            while j < n and pat[j] == "*":
                j += 1
            double = j - i >= 2
            if double and j < n and pat[j] == "/" and (i == 0 or pat[i - 1] == "/"):
                out.append("(?:[^/]+/)*")  # leading '**/' — any depth, including zero
                i = j + 1
                continue
            out.append(".*" if double else "[^/]*")
            i = j
            continue
        if c == "?":
            out.append("[^/]")
            i += 1
            continue
        out.append(re.escape(c))
        i += 1
    return "".join(out)


def _glob_pattern(pat: str) -> re.Pattern:
    cached = _GLOB_CACHE.get(pat)
    if cached is None:
        flags = 0 if os.name != "nt" else re.IGNORECASE
        cached = re.compile(rf"(?:{_translate_glob(pat)})", flags)
        _GLOB_CACHE[pat] = cached
    return cached


def rule_matches_path(rule: Rule, filepath: str, base: Optional[Path] = None) -> bool:
    """Cursor-style match: pattern with '/' matches the root-relative path,
    a bare pattern matches the basename at any depth."""
    if not rule.globs:
        return False
    p = Path(filepath).expanduser()
    if not p.is_absolute():
        p = (base if base is not None else session_cwd()) / p
    try:
        p = p.resolve()
        rel = p.relative_to(rule.root).as_posix()
    except (ValueError, OSError):
        rel = p.as_posix()
    base_name = rel.rsplit("/", 1)[-1]
    for pat in rule.globs:
        if "/" in pat:
            if _glob_pattern(pat).fullmatch(rel):
                return True
        elif _glob_pattern(pat).fullmatch(base_name):
            return True
    return False


def rules_for_paths(paths: List[str], base: Optional[Path] = None, modes=(MODE_GLOB,)) -> List[Rule]:
    """Glob-mode rules matching any of *paths*."""
    if not paths:
        return []
    root_base = base if base is not None else session_cwd()
    matched: Dict[str, Rule] = {}
    for rule in load_rules(root_base):
        if rule.mode not in modes:
            continue
        if any(rule_matches_path(rule, p, base=root_base) for p in paths if isinstance(p, str) and p):
            matched[rule.key] = rule
    return list(matched.values())


# --------------------------------------------------------------------------
# tool-arg path extraction

_PATH_ARG_KEYS = ("path", "file_path")


def candidate_paths(tool_name: str, args: Dict[str, Any]) -> List[str]:
    """Filesystem paths a tool call touches (best-effort, low-noise)."""
    if not isinstance(args, dict):
        return []
    found: List[str] = []
    for key in _PATH_ARG_KEYS:
        value = args.get(key)
        if isinstance(value, str) and value:
            found.append(value)
    if tool_name == "terminal":
        workdir = args.get("workdir")
        if isinstance(workdir, str) and workdir:
            found.append(workdir)
    unique: List[str] = []
    for item in found:
        if item not in unique:
            unique.append(item)
    return unique


# --------------------------------------------------------------------------
# per-session injection state


def _session_bucket(session_id: str) -> Dict[str, bool]:
    key = session_id or "default"
    with _STATE_LOCK:
        return _INJECTED.setdefault(key, {})


def mark_injected(session_id: str, rule_key: str) -> bool:
    """Record a full injection; True when this was the first one this session."""
    bucket = _session_bucket(session_id)
    with _STATE_LOCK:
        if bucket.get(rule_key):
            return False
        bucket[rule_key] = True
        return True


def reset_session(session_id: str) -> None:
    with _STATE_LOCK:
        _INJECTED.pop(session_id or "default", None)


def injected_count(session_id: str) -> int:
    with _STATE_LOCK:
        return len(_INJECTED.get(session_id or "default", {}))
