"""sync-from-claude: import handwritten .claude/rules/*.md into .cursor/rules/*.mdc.

Contract (spec agreed with the user):
- propose (no args): read-only plan. Per rule: ready | ask | conflict | imported.
- apply <name> [mode] [args...] [--force] [--as <new>] [--root <dir>]: write one .mdc, body verbatim.
  mode: always | glob <globs...> | desc <text...> | manual  (omitted -> from frontmatter)
- Source .md is rewritten in place as a generated projection of the new .mdc.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != REPO.resolve()]


def _load_plugin():
    name = "context_rules_plugin"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, REPO / "__init__.py", submodule_search_locations=[str(REPO)])
    module = importlib.util.module_from_spec(spec)
    module.__package__ = name
    module.__path__ = [str(REPO)]
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_plugin = _load_plugin()
core = _plugin.core
sync_rules = _plugin.sync_rules
sync_from_claude = _plugin.sync_from_claude


def mdc(tmp_path: Path, name: str, front: str, body: str) -> Path:
    p = tmp_path / ".cursor" / "rules" / f"{name}.mdc"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(f"---\n{front}\n---\n\n{body}\n")
    return p


def claude_md(project: Path, name: str, text: str) -> Path:
    p = project / ".claude" / "rules" / f"{name}.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return p


def make_project(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir(exist_ok=True)
    (tmp_path / ".cursor" / "rules").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    return tmp_path


def cursor_rule(project, name):
    """The imported canonical rule (source == 'cursor'); the kept source .md is excluded."""
    matches = [r for r in core.load_rules(project) if r.name == name and r.source == "cursor"]
    assert matches, f"no cursor rule {name}: {[r.name for r in core.load_rules(project)]}"
    rule, = matches
    return rule


def test_propose_ready_with_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: src/**/*.py\n---\n\nUse 4-space indent.\n")
    report = sync_from_claude.propose(project)
    assert "style" in report
    assert "ready" in report
    assert "src/**/*.py" in report
    assert "ask" not in report


def test_propose_ask_without_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain handwritten rule body.\n")
    report = sync_from_claude.propose(project)
    assert "team" in report
    assert "ask" in report
    assert "mode" in report  # names the unknown


def test_propose_skips_generated_projections(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "gen", "<!-- generated by hermes context-rules from .cursor/rules/gen.mdc — do not edit here; edit the .mdc. -->\nbody\n")
    report = sync_from_claude.propose(project)
    assert "] gen" not in report  # not listed as importable (only prose mentions projections)


def test_propose_conflict_when_mdc_differs(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "style", "globs: **/*.py", "Old canonical body.")
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nNew imported body.\n")
    report = sync_from_claude.propose(project)
    assert "conflict" in report
    assert "style" in report


def test_propose_imported_when_mdc_identical(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nSame body.\n")
    mdc(project, "style", "globs: **/*.py", "Same body.")
    report = sync_from_claude.propose(project)
    assert "imported" in report
    assert "style" in report


def test_propose_empty(tmp_path):
    project = make_project(tmp_path)
    assert "no" in sync_from_claude.propose(project).lower()


def test_apply_ready_without_mode_uses_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: src/**/*.py\nalwaysApply: false\n---\n\nUse 4-space indent.\n")
    out = sync_from_claude.apply(project, "style")
    assert "style" in out
    rule = cursor_rule(project, 'style')
    assert rule.source == "cursor"
    assert rule.mode == "glob"
    assert rule.globs == ["src/**/*.py"]
    assert rule.body == "Use 4-space indent."


def test_apply_ask_with_mode_writes_mdc(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    out = sync_from_claude.apply(project, "team", "always")
    assert "team" in out
    rule = cursor_rule(project, 'team')
    assert rule.mode == "always"
    assert rule.body == "Plain body."


def test_apply_glob_takes_globs(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "Body.\n")
    sync_from_claude.apply(project, "py", "glob", "src/**/*.py", "**/*.pyi")
    rule = cursor_rule(project, 'py')
    assert rule.mode == "glob"
    assert rule.globs == ["src/**/*.py", "**/*.pyi"]


def test_apply_desc_takes_text(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", "DB migration guardrails")
    rule = cursor_rule(project, 'db')
    assert rule.mode == "desc"
    assert rule.description == "DB migration guardrails"


def test_apply_manual(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "note", "Body.\n")
    sync_from_claude.apply(project, "note", "manual")
    rule = cursor_rule(project, 'note')
    assert rule.mode == "manual"


def test_apply_ask_without_mode_errors(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    out = sync_from_claude.apply(project, "team")
    assert "mode" in out.lower()


def test_apply_unknown_rule_errors(tmp_path):
    project = make_project(tmp_path)
    out = sync_from_claude.apply(project, "ghost")
    assert "ghost" in out


def test_apply_conflict_needs_force(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "style", "globs: **/*.py", "Old canonical body.")
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nNew imported body.\n")
    out = sync_from_claude.apply(project, "style")
    assert "conflict" in out
    assert "New imported" not in (project / ".cursor" / "rules" / "style.mdc").read_text()
    out2 = sync_from_claude.apply(project, "style", "--force")
    assert "style" in out2
    assert "New imported body" in (project / ".cursor" / "rules" / "style.mdc").read_text()


def test_apply_as_renames(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    assert (project / ".cursor" / "rules" / "python-style.mdc").exists()
    assert not (project / ".cursor" / "rules" / "style.mdc").exists()
    # the projection references the renamed .mdc; sync consolidates to the
    # managed name and prunes the pre-rename duplicate
    sync_rules.sync(str(project))
    proj = (project / ".claude" / "rules" / "python-style.md")
    assert proj.exists()
    assert not (project / ".claude" / "rules" / "style.md").exists()


def test_apply_dangling_as_errors(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "x", "Body.\n")
    out = sync_from_claude.apply(project, "x", "always", "--as")
    assert "usage" in out.lower()
    assert not list((project / ".cursor" / "rules").glob("*.mdc"))


def test_apply_creates_missing_cursor_rules_dir(tmp_path):
    project = tmp_path
    (project / ".git").mkdir()
    claude_md(project, "team", "Plain body.\n")  # .claude only, no .cursor/rules
    out = sync_from_claude.apply(project, "team", "always")
    assert "team" in out
    assert (project / ".cursor" / "rules" / "team.mdc").exists()


def test_apply_keeps_source_md_as_projection(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    sync_from_claude.apply(project, "team", "always")
    src = (project / ".claude" / "rules" / "team.md")
    assert src.exists()
    text = src.read_text()
    assert "generated by hermes context-rules" in text
    assert "Plain body." in text


def test_apply_then_sync_never_counts_always_rule_twice(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    sync_from_claude.apply(project, "team", "always")
    sync_rules.sync(str(project))
    names = [r.name for r in core.load_rules(project)]
    assert names.count("team") == 1


def test_apply_desc_text_is_yaml_quoted(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", "yes: runs on every deploy #critical")
    rule = cursor_rule(project, "db")
    assert rule.mode == "desc"  # 'yes' did not become a YAML boolean
    assert rule.description == "yes: runs on every deploy #critical"


def test_apply_carries_enforce_key(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\nenforce: ruff check .\n---\n\nBody.\n")
    sync_from_claude.apply(project, "py")
    rule = cursor_rule(project, "py")
    assert rule.enforce == "ruff check ."


def test_propose_survives_undecodable_mdc(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    (project / ".cursor" / "rules" / "broken.mdc").write_bytes(b"\xff\xfe\x00bad")
    report = sync_from_claude.propose(project)
    assert "team" in report


def test_apply_then_sync_makes_projection(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\n---\n\nImported rule.\n")
    sync_from_claude.apply(project, "py")
    sync_rules.sync(str(project))
    names = [r.name for r in core.load_rules(project)]
    assert names.count("py") == 1  # projection not double-counted
    proj = (project / ".claude" / "rules" / "py.md").read_text()
    assert "generated by hermes context-rules" in proj
    assert "Imported rule." in proj


def test_sync_refreshes_always_mode_projection(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "team", "alwaysApply: true", "Old body.")
    sync_rules.sync(str(project))
    # canon edited later; sync must refresh the always-mode projection too
    mdc(project, "team", "alwaysApply: true", "New body.")
    sync_rules.sync(str(project))
    proj = (project / ".claude" / "rules" / "team.md").read_text()
    assert "New body." in proj
    assert "Apply unconditionally." in proj


def test_sync_removes_stale_duplicate_projection_after_rename(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    # style.md (projection of python-style.mdc) + sync's own python-style.md
    sync_rules.sync(str(project))
    assert (project / ".claude" / "rules" / "python-style.md").exists()
    assert not (project / ".claude" / "rules" / "style.md").exists()  # duplicate pruned
    names = [r.name for r in core.load_rules(project)]
    assert names.count("python-style") == 1


def test_sync_refreshes_renamed_projection_after_canon_edit(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nOld body.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    mdc(project, "python-style", "globs: **/*.py", "New body.")
    sync_rules.sync(str(project))
    assert not (project / ".claude" / "rules" / "style.md").exists()  # stale duplicate gone
    proj = (project / ".claude" / "rules" / "python-style.md").read_text()
    assert "New body." in proj


def test_apply_identical_body_fixup_preserves_canon(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\n---\n\nSame body.\n")
    mdc(project, "py", "globs: **/*.py\ndescription: kept", "Same body.")
    out = sync_from_claude.apply(project, "py")  # 'imported' fix-up, no mode given
    assert "canon unchanged" in out
    canon = (project / ".cursor" / "rules" / "py.mdc").read_text()
    assert "description: kept" in canon  # canon-only key untouched
    rule = cursor_rule(project, "py")
    assert rule.mode == "glob"  # semantics unchanged
    proj = (project / ".claude" / "rules" / "py.md").read_text()
    assert "generated by hermes context-rules" in proj
    assert "py.mdc" in proj


def test_apply_same_name_two_roots_requires_disambiguation(tmp_path):
    outer = tmp_path  # git root
    inner = tmp_path / "pkg"
    (outer / ".git").mkdir(exist_ok=True)
    (outer / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    (inner / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    (outer / ".claude" / "rules" / "py.md").write_text("Outer body.\n")
    (inner / ".claude" / "rules" / "py.md").write_text("Inner body.\n")
    # from inner, the upward chain sees both roots' same-named rule
    report = sync_from_claude.propose(inner)
    assert "root:" in report  # propose flags the ambiguity
    out = sync_from_claude.apply(inner, "py", "always")
    assert "disambiguate" in out
    assert not (inner / ".cursor").exists()  # nothing written yet
    out2 = sync_from_claude.apply(inner, "py", "always", "--root", str(inner))
    assert "imported" in out2
    assert (inner / ".cursor" / "rules" / "py.mdc").exists()
    assert not (outer / ".cursor" / "rules" / "py.mdc").exists()


def test_apply_always_mode_keeps_source_globs(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nalwaysApply: true\nglobs: src/**/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "py")  # mode from frontmatter: always
    rule = cursor_rule(project, "py")
    assert rule.mode == "always"
    assert rule.globs == ["src/**/*.py"]  # kept for a later alwaysApply flip


def test_frontmatter_quoting_roundtrips_without_pyyaml(tmp_path):
    project = make_project(tmp_path)
    tricky = 'He said "stop" café #note'
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", tricky)
    text = (project / ".cursor" / "rules" / "db.mdc").read_text(encoding="utf-8-sig")
    # parse the written canon with the FALLBACK parser (PyYAML absent)
    saved_yaml = core.yaml
    core.yaml = None
    try:
        meta, _ = core._parse_frontmatter(text)
        assert meta.get("description") == tricky
        meta2, _ = core._parse_frontmatter("---\nglobs: [\"src/{a,b}/*.py\", \"plain.py\"]\n---\nbody")
        assert meta2.get("globs") == ["src/{a,b}/*.py", "plain.py"]
    finally:
        core.yaml = saved_yaml


def test_apply_none_valued_key_not_stringified(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "x", "---\nglobs: **/*.py\nexperimental:\n---\n\nBody.\n")
    sync_from_claude.apply(project, "x")
    canon = (project / ".cursor" / "rules" / "x.mdc").read_text()
    assert "None" not in canon


def test_sync_prunes_orphan_projection_without_canon(tmp_path):
    project = make_project(tmp_path)
    (project / ".claude" / "rules" / "ghost.md").write_text(
        "<!-- generated by hermes context-rules from .cursor/rules/ghost.mdc — do not edit here; edit the .mdc. -->\n\nBody.\n")
    out = sync_rules.sync(str(project))
    assert not (project / ".claude" / "rules" / "ghost.md").exists()
    assert "removed: ghost.md" in out
