"""sync-from-claude: import handwritten .claude/rules/*.md into .cursor/rules/*.mdc.

Contract (spec agreed with the user):
- propose (no args): read-only plan. Per rule: ready | ask | conflict | imported.
- apply <name> [mode] [args...] [--force] [--as <new>] [--root <dir>]: write one .mdc, body verbatim.
  mode: always | glob <globs...> | desc <text...> | manual  (omitted -> from frontmatter)
- Source .md is rewritten in place as a generated projection of the new .mdc.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != REPO.resolve()]


def _load_plugin():
    name = "context_rules_plugin"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, REPO / "__init__.py", submodule_search_locations=[str(REPO)])
    module = importlib.util.module_from_spec(spec)
    module.__package__ = name
    module.__path__ = [str(REPO)]
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_plugin = _load_plugin()
core = _plugin.core
sync_rules = _plugin.sync_rules
sync_from_claude = _plugin.sync_from_claude


def mdc(tmp_path: Path, name: str, front: str, body: str) -> Path:
    p = tmp_path / ".cursor" / "rules" / f"{name}.mdc"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(f"---\n{front}\n---\n\n{body}\n")
    return p


def claude_md(project: Path, name: str, text: str) -> Path:
    p = project / ".claude" / "rules" / f"{name}.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return p


def make_project(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir(exist_ok=True)
    (tmp_path / ".cursor" / "rules").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    return tmp_path


def cursor_rule(project, name):
    """The imported canonical rule (source == 'cursor'); the kept source .md is excluded."""
    matches = [r for r in core.load_rules(project) if r.name == name and r.source == "cursor"]
    assert matches, f"no cursor rule {name}: {[r.name for r in core.load_rules(project)]}"
    rule, = matches
    return rule


def test_propose_ready_with_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: src/**/*.py\n---\n\nUse 4-space indent.\n")
    report = sync_from_claude.propose(project)
    assert "style" in report
    assert "ready" in report
    assert "src/**/*.py" in report
    assert "ask" not in report


def test_propose_ask_without_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain handwritten rule body.\n")
    report = sync_from_claude.propose(project)
    assert "team" in report
    assert "ask" in report
    assert "mode" in report  # names the unknown


def test_propose_skips_generated_projections(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "gen", "<!-- generated by hermes context-rules from .cursor/rules/gen.mdc — do not edit here; edit the .mdc. -->\nbody\n")
    report = sync_from_claude.propose(project)
    assert "] gen" not in report  # not listed as importable (only prose mentions projections)


def test_propose_conflict_when_mdc_differs(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "style", "globs: **/*.py", "Old canonical body.")
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nNew imported body.\n")
    report = sync_from_claude.propose(project)
    assert "conflict" in report
    assert "style" in report


def test_propose_imported_when_mdc_identical(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nSame body.\n")
    mdc(project, "style", "globs: **/*.py", "Same body.")
    report = sync_from_claude.propose(project)
    assert "imported" in report
    assert "style" in report


def test_propose_empty(tmp_path):
    project = make_project(tmp_path)
    assert "no" in sync_from_claude.propose(project).lower()


def test_apply_ready_without_mode_uses_frontmatter(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: src/**/*.py\nalwaysApply: false\n---\n\nUse 4-space indent.\n")
    out = sync_from_claude.apply(project, "style")
    assert "style" in out
    rule = cursor_rule(project, 'style')
    assert rule.source == "cursor"
    assert rule.mode == "glob"
    assert rule.globs == ["src/**/*.py"]
    assert rule.body == "Use 4-space indent."


def test_apply_ask_with_mode_writes_mdc(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    out = sync_from_claude.apply(project, "team", "always")
    assert "team" in out
    rule = cursor_rule(project, 'team')
    assert rule.mode == "always"
    assert rule.body == "Plain body."


def test_apply_glob_takes_globs(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "Body.\n")
    sync_from_claude.apply(project, "py", "glob", "src/**/*.py", "**/*.pyi")
    rule = cursor_rule(project, 'py')
    assert rule.mode == "glob"
    assert rule.globs == ["src/**/*.py", "**/*.pyi"]


def test_apply_desc_takes_text(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", "DB migration guardrails")
    rule = cursor_rule(project, 'db')
    assert rule.mode == "desc"
    assert rule.description == "DB migration guardrails"


def test_apply_manual(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "note", "Body.\n")
    sync_from_claude.apply(project, "note", "manual")
    rule = cursor_rule(project, 'note')
    assert rule.mode == "manual"


def test_apply_ask_without_mode_errors(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    out = sync_from_claude.apply(project, "team")
    assert "mode" in out.lower()


def test_apply_unknown_rule_errors(tmp_path):
    project = make_project(tmp_path)
    out = sync_from_claude.apply(project, "ghost")
    assert "ghost" in out


def test_apply_conflict_needs_force(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "style", "globs: **/*.py", "Old canonical body.")
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nNew imported body.\n")
    out = sync_from_claude.apply(project, "style")
    assert "conflict" in out
    assert "New imported" not in (project / ".cursor" / "rules" / "style.mdc").read_text()
    out2 = sync_from_claude.apply(project, "style", "--force")
    assert "style" in out2
    assert "New imported body" in (project / ".cursor" / "rules" / "style.mdc").read_text()


def test_apply_as_renames(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    assert (project / ".cursor" / "rules" / "python-style.mdc").exists()
    assert not (project / ".cursor" / "rules" / "style.mdc").exists()
    # the projection references the renamed .mdc; sync consolidates to the
    # managed name and prunes the pre-rename duplicate
    sync_rules.sync(str(project))
    proj = (project / ".claude" / "rules" / "python-style.md")
    assert proj.exists()
    assert not (project / ".claude" / "rules" / "style.md").exists()


def test_apply_dangling_as_errors(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "x", "Body.\n")
    out = sync_from_claude.apply(project, "x", "always", "--as")
    assert "usage" in out.lower()
    assert not list((project / ".cursor" / "rules").glob("*.mdc"))


def test_apply_creates_missing_cursor_rules_dir(tmp_path):
    project = tmp_path
    (project / ".git").mkdir()
    claude_md(project, "team", "Plain body.\n")  # .claude only, no .cursor/rules
    out = sync_from_claude.apply(project, "team", "always")
    assert "team" in out
    assert (project / ".cursor" / "rules" / "team.mdc").exists()


def test_apply_keeps_source_md_as_projection(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    sync_from_claude.apply(project, "team", "always")
    src = (project / ".claude" / "rules" / "team.md")
    assert src.exists()
    text = src.read_text()
    assert "generated by hermes context-rules" in text
    assert "Plain body." in text


def test_apply_then_sync_never_counts_always_rule_twice(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    sync_from_claude.apply(project, "team", "always")
    sync_rules.sync(str(project))
    names = [r.name for r in core.load_rules(project)]
    assert names.count("team") == 1


def test_apply_desc_text_is_yaml_quoted(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", "yes: runs on every deploy #critical")
    rule = cursor_rule(project, "db")
    assert rule.mode == "desc"  # 'yes' did not become a YAML boolean
    assert rule.description == "yes: runs on every deploy #critical"


def test_apply_carries_enforce_key(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\nenforce: ruff check .\n---\n\nBody.\n")
    sync_from_claude.apply(project, "py")
    rule = cursor_rule(project, "py")
    assert rule.enforce == "ruff check ."


def test_propose_survives_undecodable_mdc(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")
    (project / ".cursor" / "rules" / "broken.mdc").write_bytes(b"\xff\xfe\x00bad")
    report = sync_from_claude.propose(project)
    assert "team" in report


def test_apply_then_sync_makes_projection(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\n---\n\nImported rule.\n")
    sync_from_claude.apply(project, "py")
    sync_rules.sync(str(project))
    names = [r.name for r in core.load_rules(project)]
    assert names.count("py") == 1  # projection not double-counted
    proj = (project / ".claude" / "rules" / "py.md").read_text()
    assert "generated by hermes context-rules" in proj
    assert "Imported rule." in proj


def test_sync_refreshes_always_mode_projection(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "team", "alwaysApply: true", "Old body.")
    sync_rules.sync(str(project))
    # canon edited later; sync must refresh the always-mode projection too
    mdc(project, "team", "alwaysApply: true", "New body.")
    sync_rules.sync(str(project))
    proj = (project / ".claude" / "rules" / "team.md").read_text()
    assert "New body." in proj
    assert "Apply unconditionally." in proj


def test_sync_removes_stale_duplicate_projection_after_rename(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    # style.md (projection of python-style.mdc) + sync's own python-style.md
    sync_rules.sync(str(project))
    assert (project / ".claude" / "rules" / "python-style.md").exists()
    assert not (project / ".claude" / "rules" / "style.md").exists()  # duplicate pruned
    names = [r.name for r in core.load_rules(project)]
    assert names.count("python-style") == 1


def test_sync_refreshes_renamed_projection_after_canon_edit(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nOld body.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    mdc(project, "python-style", "globs: **/*.py", "New body.")
    sync_rules.sync(str(project))
    assert not (project / ".claude" / "rules" / "style.md").exists()  # stale duplicate gone
    proj = (project / ".claude" / "rules" / "python-style.md").read_text()
    assert "New body." in proj


def test_apply_identical_body_fixup_preserves_canon(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nglobs: **/*.py\n---\n\nSame body.\n")
    mdc(project, "py", "globs: **/*.py\ndescription: kept", "Same body.")
    out = sync_from_claude.apply(project, "py")  # 'imported' fix-up, no mode given
    assert "canon unchanged" in out
    canon = (project / ".cursor" / "rules" / "py.mdc").read_text()
    assert "description: kept" in canon  # canon-only key untouched
    rule = cursor_rule(project, "py")
    assert rule.mode == "glob"  # semantics unchanged
    proj = (project / ".claude" / "rules" / "py.md").read_text()
    assert "generated by hermes context-rules" in proj
    assert "py.mdc" in proj


def test_apply_same_name_two_roots_requires_disambiguation(tmp_path):
    outer = tmp_path  # git root
    inner = tmp_path / "pkg"
    (outer / ".git").mkdir(exist_ok=True)
    (outer / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    (inner / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    (outer / ".claude" / "rules" / "py.md").write_text("Outer body.\n")
    (inner / ".claude" / "rules" / "py.md").write_text("Inner body.\n")
    # from inner, the upward chain sees both roots' same-named rule
    report = sync_from_claude.propose(inner)
    assert "root:" in report  # propose flags the ambiguity
    out = sync_from_claude.apply(inner, "py", "always")
    assert "disambiguate" in out
    assert not (inner / ".cursor").exists()  # nothing written yet
    out2 = sync_from_claude.apply(inner, "py", "always", "--root", str(inner))
    assert "imported" in out2
    assert (inner / ".cursor" / "rules" / "py.mdc").exists()
    assert not (outer / ".cursor" / "rules" / "py.mdc").exists()


def test_apply_always_mode_keeps_source_globs(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "py", "---\nalwaysApply: true\nglobs: src/**/*.py\n---\n\nBody.\n")
    sync_from_claude.apply(project, "py")  # mode from frontmatter: always
    rule = cursor_rule(project, "py")
    assert rule.mode == "always"
    assert rule.globs == ["src/**/*.py"]  # kept for a later alwaysApply flip


def test_frontmatter_quoting_roundtrips_without_pyyaml(tmp_path):
    project = make_project(tmp_path)
    tricky = 'He said "stop" café #note'
    claude_md(project, "db", "Body.\n")
    sync_from_claude.apply(project, "db", "desc", tricky)
    text = (project / ".cursor" / "rules" / "db.mdc").read_text(encoding="utf-8-sig")
    # parse the written canon with the FALLBACK parser (PyYAML absent)
    saved_yaml = core.yaml
    core.yaml = None
    try:
        meta, _ = core._parse_frontmatter(text)
        assert meta.get("description") == tricky
        meta2, _ = core._parse_frontmatter("---\nglobs: [\"src/{a,b}/*.py\", \"plain.py\"]\n---\nbody")
        assert meta2.get("globs") == ["src/{a,b}/*.py", "plain.py"]
    finally:
        core.yaml = saved_yaml


def test_apply_none_valued_key_not_stringified(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "x", "---\nglobs: **/*.py\nexperimental:\n---\n\nBody.\n")
    sync_from_claude.apply(project, "x")
    canon = (project / ".cursor" / "rules" / "x.mdc").read_text()
    assert "None" not in canon


def test_sync_prunes_orphan_projection_without_canon(tmp_path):
    project = make_project(tmp_path)
    (project / ".claude" / "rules" / "ghost.md").write_text(
        "<!-- generated by hermes context-rules from .cursor/rules/ghost.mdc — do not edit here; edit the .mdc. -->\n\nBody.\n")
    out = sync_rules.sync(str(project))
    assert not (project / ".claude" / "rules" / "ghost.md").exists()
    assert "removed: ghost.md" in out


def test_sync_never_overwrites_handwritten_claude_rule(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "deploy", "alwaysApply: true", "Canon body.")
    (project / ".claude" / "rules" / "deploy.md").write_text("Handwritten deploy wisdom.\n")
    out = sync_rules.sync(str(project))
    src = (project / ".claude" / "rules" / "deploy.md").read_text()
    assert src == "Handwritten deploy wisdom.\n"  # untouched
    assert "skipped" in out and "handwritten" in out
    # both rules coexist as distinct rules (collisions coexist by design)
    names = [(r.name, r.source) for r in core.load_rules(project)]
    assert ("deploy", "cursor") in names and ("deploy", "claude") in names


def test_sync_reports_slug_collision_instead_of_clobbering(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "my rule", "globs: **/*.py", "Body one.")
    mdc(project, "my-rule", "globs: **/*.py", "Body two.")
    out = sync_rules.sync(str(project))
    assert "collision" in out
    # exactly one projection written; the collision is surfaced, not silent
    projs = list((project / ".claude" / "rules").glob("*.md"))
    assert len(projs) == 1


def test_sync_keeps_projection_of_unparseable_canon(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "py", "globs: **/*.py", "Body.")
    sync_rules.sync(str(project))  # creates projection
    # canon becomes unreadable (but still exists)
    (project / ".cursor" / "rules" / "py.mdc").write_bytes(b"\xff\xfe\x00bad")
    sync_rules.sync(str(project))
    assert (project / ".claude" / "rules" / "py.md").exists()  # not pruned


def test_apply_empty_body_canon_needs_force(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "team", "alwaysApply: true", "")  # canon with empty body
    claude_md(project, "team", "New body.\n")
    out = sync_from_claude.apply(project, "team", "always")
    assert "conflict" in out
    assert "New body." not in (project / ".cursor" / "rules" / "team.mdc").read_text()


def test_apply_explicit_mode_matching_canon_preserves_it(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "py", "alwaysApply: true\nglobs: src/**/*.py", "Same body.")
    claude_md(project, "py", "---\nalwaysApply: true\nglobs: src/**/*.py\n---\n\nSame body.\n")
    out = sync_from_claude.apply(project, "py", "always")  # explicit mode == canon mode
    assert "canon unchanged" in out
    canon = (project / ".cursor" / "rules" / "py.mdc").read_text()
    assert "globs: src/**/*.py" in canon  # canon keys preserved


def test_fallback_parser_escaped_quote_in_flow_list(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "q", "Body.\n")
    sync_from_claude.apply(project, "q", "glob", 'a"b.py', "plain.py")
    text = (project / ".cursor" / "rules" / "q.mdc").read_text(encoding="utf-8-sig")
    saved = core.yaml
    core.yaml = None
    try:
        meta, _ = core._parse_frontmatter(text)
        assert meta.get("globs") == ['a"b.py', "plain.py"], meta
    finally:
        core.yaml = saved


def test_fallback_parser_block_list_roundtrips_into_canon(tmp_path):
    project = make_project(tmp_path)
    # unquoted **/*.py makes PyYAML raise -> fallback parser handles it
    claude_md(project, "x", "---\nglobs: **/*.py\ntags:\n  - a\n  - b\n---\n\nBody.\n")
    sync_from_claude.apply(project, "x")
    canon = (project / ".cursor" / "rules" / "x.mdc").read_text()
    assert "tags" in canon  # block list survived the import, not silently dropped


def test_apply_desc_boolean_not_stringified(tmp_path):
    project = make_project(tmp_path)
    # PyYAML parses 'yes' as True; the raw text must not become "True"
    claude_md(project, "db", "---\ndescription: yes\n---\n\nBody.\n")
    out = sync_from_claude.apply(project, "db")  # no explicit mode
    assert "a mode is required" in out  # explicit error, no silent "True" canon
    assert not (project / ".cursor" / "rules" / "db.mdc").exists()
    out2 = sync_from_claude.apply(project, "db", "desc", "yes")
    assert "imported" in out2
    canon = (project / ".cursor" / "rules" / "db.mdc").read_text()
    assert '"yes"' in canon and "True" not in canon


def test_sync_keeps_only_projection_when_managed_name_occupied(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "style", "---\nglobs: **/*.py\n---\n\nBody.\n")
    # pre-existing handwritten file occupying the rename target's projection name
    (project / ".claude" / "rules" / "python-style.md").write_text("Handwritten note.\n")
    sync_from_claude.apply(project, "style", "--as", "python-style")
    out = sync_rules.sync(str(project))
    # the marked pre-rename projection (style.md) is the canon's only projection
    assert (project / ".claude" / "rules" / "style.md").exists()
    assert (project / ".claude" / "rules" / "python-style.md").read_text() == "Handwritten note.\n"
    assert "skipped" in out


def test_apply_frontmatterless_identical_body_allows_fixup(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "team", "Plain body.\n")  # no frontmatter
    mdc(project, "team", "alwaysApply: true", "Plain body.")
    out = sync_from_claude.apply(project, "team")  # no mode given
    assert "canon unchanged" in out
    proj = (project / ".claude" / "rules" / "team.md").read_text()
    assert "generated by hermes context-rules" in proj


def test_apply_source_md_restored_when_projection_rewrite_fails(tmp_path, monkeypatch):
    """Mid-write failure must never lose the handwritten rule (data loss)."""
    project = make_project(tmp_path)
    src = claude_md(project, "db", "---\ndescription: notes\n---\n\nHandwritten wisdom.\n")
    original = src.read_bytes()

    real_write_text = Path.write_text

    def failing_write_text(self, data, encoding=None, errors=None, newline=None):
        if self.name == "db.md":  # the projection rewrite (2nd write), not the canon
            raise OSError(28, "No space left on device")
        return real_write_text(self, data, encoding=encoding, errors=errors, newline=newline)

    monkeypatch.setattr(Path, "write_text", failing_write_text)
    out = sync_from_claude.apply(project, "db")
    monkeypatch.undo()
    assert "import failed" in out
    # both files survive: source restored byte-for-byte, canon rolled back
    assert src.read_bytes() == original
    assert not (project / ".cursor" / "rules" / "db.mdc").exists()


def test_apply_as_rejects_path_separators_and_dots(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "db", "Body.\n")
    for bad in ("..", ".", "a/b", "a\\b", "../evil", " -x"):
        out = sync_from_claude.apply(project, "db", "--as", bad)
        assert "invalid --as name" in out, bad
    assert not (project / "evil.mdc").exists()


def test_handle_quotes_name_with_spaces(tmp_path, monkeypatch):
    project = make_project(tmp_path)
    claude_md(project, "my rule", "Body.\n")
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    out = sync_from_claude.handle('apply "my rule" manual')
    assert "imported my rule" in out
    assert (project / ".cursor" / "rules" / "my rule.mdc").exists()


def test_emit_serializes_opaque_values_as_json(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "meta", "---\ntags:\n  - a\n  - b\n---\n\nBody.\n")
    sync_from_claude.apply(project, "meta", "manual")
    canon = (project / ".cursor" / "rules" / "meta.mdc").read_text(encoding="utf-8-sig")
    fm, _ = core._parse_frontmatter(canon)
    assert fm.get("tags") == ["a", "b"], canon  # re-parseable, not a Python repr string


def test_handle_slash_preserves_double_space_in_quoted_name(tmp_path, monkeypatch):
    """CodeRabbit: _handle_slash re-joined split() tokens, collapsing the
    double space in "a  b" to "a b" before handle() could parse it."""
    project = make_project(tmp_path)
    claude_md(project, "a  b", "Body.\n")
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    out = _plugin._handle_slash('sync-from-claude apply "a  b" manual')
    assert "imported a  b" in out
    assert (project / ".cursor" / "rules" / "a  b.mdc").exists()


def test_apply_writes_body_verbatim(tmp_path):
    """Sourcery :323 — the body is copied without .strip(): leading spaces
    and trailing blank lines survive to the canon and the projection.
    (The parser itself normalizes the blank line right after ``---`` and
    the final newline; the reference is the parsed source body.)"""
    project = make_project(tmp_path)
    raw = "---\nalwaysApply: true\n---\n\n\n   Padded wisdom.   \n\n\n"
    claude_md(project, "padded", raw)
    _, parsed_body = core._parse_frontmatter(raw)
    assert parsed_body == "   Padded wisdom.   \n\n"  # the parser's verbatim view
    out = sync_from_claude.apply(project, "padded")
    assert "imported padded" in out
    canon = (project / ".cursor" / "rules" / "padded.mdc").read_text(encoding="utf-8-sig")
    _, canon_body = core._parse_frontmatter(canon)
    assert canon_body == parsed_body, canon
    proj = (project / ".claude" / "rules" / "padded.md").read_text(encoding="utf-8-sig")
    assert proj.endswith(parsed_body + "\n"), proj  # same unstripped body


def test_apply_rejects_whitespace_only_body(tmp_path):
    project = make_project(tmp_path)
    claude_md(project, "empty", "---\nalwaysApply: true\n---\n\n   \n\t\n")
    out = sync_from_claude.apply(project, "empty")
    assert "empty body" in out
    assert not (project / ".cursor" / "rules" / "empty.mdc").exists()


def test_propose_non_string_description_is_not_ready(tmp_path):
    """Sourcery :79 — description: yes parsed as boolean True must not
    resolve to desc mode via str(True); propose reports 'ask' and apply
    without an explicit mode refuses (propose/apply agree)."""
    project = make_project(tmp_path)
    claude_md(project, "truthy", "---\ndescription: yes\n---\n\nBody.\n")
    report = sync_from_claude.propose(project)
    assert "description: True" not in report  # never a desc mode from str(True)
    assert "ask" in report and "not a usable string" in report
    # apply without a mode refuses instead of importing manual silently
    out = sync_from_claude.apply(project, "truthy")
    assert "a mode is required" in out
    assert not (project / ".cursor" / "rules" / "truthy.mdc").exists()
    # an explicit mode is the way through
    out2 = sync_from_claude.apply(project, "truthy", "manual")
    assert "imported truthy" in out2


def test_apply_non_string_description_desc_mode_needs_text(tmp_path):
    """desc mode with no text and a non-string meta description errors."""
    project = make_project(tmp_path)
    claude_md(project, "truthy", "---\ndescription: on\n---\n\nBody.\n")
    out = sync_from_claude.apply(project, "truthy", "desc")
    assert "desc mode needs a description" in out


def test_fallback_parser_decodes_json_flow_mapping():
    """Sourcery :154 — the fallback must restore the dicts _emit() writes."""
    text = 'meta: {"k": "v", "n": 1, "nested": {"deep": [true, null]}}\n'
    parsed = core._fallback_yaml(text)
    assert parsed == {"meta": {"k": "v", "n": 1,
                               "nested": {"deep": [True, None]}}}, parsed


def test_fallback_parser_malformed_brace_value_stays_string():
    parsed = core._fallback_yaml("meta: {not json at all\n")
    assert parsed == {"meta": "{not json at all"}, parsed


def test_import_dict_metadata_survives_fallback_reparse(tmp_path, monkeypatch):
    """End-to-end: a dict-valued opaque key round-trips through the canon
    with the same type in fallback-only environments."""
    project = make_project(tmp_path)
    claude_md(project, "dicty", "---\nowner: me\n---\n\nBody.\n")
    # a dict-valued carry-over key (as if parsed from a richer source)
    item = sync_from_claude._Importable(
        project / ".claude" / "rules" / "dicty.md", project)
    item.meta["x-config"] = {"timeout": 30, "tags": ["a", "b"]}
    monkeypatch.setattr(sync_from_claude, "_collect", lambda base: [item])
    out = sync_from_claude.apply(project, "dicty", "manual")
    assert "imported dicty" in out
    canon = (project / ".cursor" / "rules" / "dicty.mdc").read_text(encoding="utf-8-sig")
    fm, _ = core._parse_frontmatter(canon)
    # PyYAML (test env) and the fallback must agree on the type
    assert fm.get("x-config") == {"timeout": 30, "tags": ["a", "b"]}, canon
    fm_line = next(ln for ln in canon.splitlines() if ln.startswith("x-config:"))
    fm_fallback = core._fallback_yaml(fm_line)
    assert fm_fallback.get("x-config") == {"timeout": 30, "tags": ["a", "b"]}, fm_line


def test_rollback_preserves_concurrent_canon_write(tmp_path, monkeypatch):
    """Sourcery :369 — a concurrent writer's canon update must survive our
    rollback after a failed projection rewrite."""
    project = make_project(tmp_path)
    src = claude_md(project, "db", "---\ndescription: notes\n---\n\nHandwritten wisdom v2.\n")
    original = src.read_bytes()
    pre_existing = mdc(project, "db", "alwaysApply: true", "Handwritten wisdom.")
    original_canon = pre_existing.read_bytes()

    real_write_text = Path.write_text

    def failing_write_text(self, data, encoding=None, errors=None, newline=None):
        if self.name == "db.md":  # the projection rewrite fails
            # a concurrent writer updates the canon between our write and rollback
            real_write_text(pre_existing, "---\nalwaysApply: true\n---\n\nRaced content.\n",
                            encoding="utf-8")
            raise OSError(28, "No space left on device")
        return real_write_text(self, data, encoding=encoding, errors=errors, newline=newline)

    monkeypatch.setattr(Path, "write_text", failing_write_text)
    out = sync_from_claude.apply(project, "db", "--force")
    monkeypatch.undo()
    assert "import failed" in out
    assert "concurrent writer" in out
    # the racer's bytes survive; the pre-import canon bytes are NOT restored
    assert pre_existing.read_bytes() != original_canon
    assert b"Raced content." in pre_existing.read_bytes()
    # source restored byte-for-byte
    assert src.read_bytes() == original


def test_rollback_restores_unchanged_canon(tmp_path, monkeypatch):
    """The guard must not break the normal restore path."""
    project = make_project(tmp_path)
    claude_md(project, "db", "---\ndescription: notes\n---\n\nHandwritten wisdom v2.\n")
    pre_existing = mdc(project, "db", "alwaysApply: true", "Handwritten wisdom.")
    original_canon = pre_existing.read_bytes()

    real_write_text = Path.write_text

    def failing_write_text(self, data, encoding=None, errors=None, newline=None):
        if self.name == "db.md":
            raise OSError(28, "No space left on device")
        return real_write_text(self, data, encoding=encoding, errors=errors, newline=newline)

    monkeypatch.setattr(Path, "write_text", failing_write_text)
    out = sync_from_claude.apply(project, "db", "--force")
    monkeypatch.undo()
    assert "import failed" in out
    assert "canon restored" in out
    assert pre_existing.read_bytes() == original_canon
