"""Standalone tests for context-rules (no Hermes imports required).

The plugin loads as a flat package (root __init__.py + sibling modules), the
same shape the Hermes loader imports; tests replicate that with importlib.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

# Mirror the real loader: the plugin dir is imported as a package, never put on
# sys.path. Keep the scrub so flat-import regressions cannot be masked here.
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != REPO.resolve()]


def _load_plugin():
    """Import the plugin package exactly once, under a stable name."""
    name = "context_rules_plugin"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, REPO / "__init__.py", submodule_search_locations=[str(REPO)])
    module = importlib.util.module_from_spec(spec)
    module.__package__ = name
    module.__path__ = [str(REPO)]
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_plugin = _load_plugin()
core = _plugin.core
enforce = _plugin.enforce
sync_rules = _plugin.sync_rules


@pytest.fixture()
def project(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir()
    (tmp_path / "src").mkdir()
    (tmp_path / ".cursor" / "rules").mkdir(parents=True)
    (tmp_path / ".claude" / "rules").mkdir(parents=True)
    (tmp_path / "src" / "app.py").write_text("x = 1\n")
    (tmp_path / "README.md").write_text("readme\n")
    return tmp_path


def mdc(tmp_path: Path, name: str, front: str, body: str) -> Path:
    p = tmp_path / ".cursor" / "rules" / f"{name}.mdc"
    p.write_text(f"---\n{front}\n---\n\n{body}\n")
    return p


# -- discovery / parsing ----------------------------------------------------


def test_fallback_yaml_booleans_match_pyyaml():
    """Fallback parser must coerce the same YAML 1.1 booleans as PyYAML.

    Mode resolution (``alwaysApply: yes``) may not depend on whether PyYAML
    happens to be installed — the plugin's runtime often has only the fallback.
    """
    for spell in ("yes", "Yes", "YES", "on", "On", "ON", "true", "True", "TRUE"):
        assert core._fallback_yaml(f"k: {spell}") == {"k": True}, spell
    for spell in ("no", "No", "NO", "off", "Off", "OFF", "false", "False", "FALSE"):
        assert core._fallback_yaml(f"k: {spell}") == {"k": False}, spell
    # single letters stayed strings in PyYAML >= 5.1 — the fallback must agree
    assert core._fallback_yaml("k: y") == {"k": "y"}
    assert core._fallback_yaml("k: N") == {"k": "N"}


def test_finds_rules_and_modes(project):
    mdc(project, "py-style", "globs: src/**/*.py\nalwaysApply: false", "Use 4-space indent.")
    mdc(project, "always-house", "alwaysApply: true", "Be terse.")
    mdc(project, "on-demand", "description: DB migration guardrails", "Always add rollback.")
    mdc(project, "manual-thing", "alwaysApply: false", "Only when asked.")
    rules = core.load_rules(project)
    modes = {r.name: r.mode for r in rules}
    assert modes == {
        "py-style": "glob",
        "always-house": "always",
        "on-demand": "desc",
        "manual-thing": "manual",
    }


def test_claude_md_without_frontmatter_is_always(project):
    (project / ".claude" / "rules" / "team.md").write_text("Plain Claude rule body.\n")
    rules = {r.name: r for r in core.load_rules(project)}
    assert rules["team"].mode == "always"
    assert rules["team"].source == "claude"


def test_generated_marker_skipped(project):
    gen = project / ".claude" / "rules" / "py-style.md"
    gen.write_text("<!-- generated by hermes context-rules from .cursor/rules/py-style.mdc — do not edit. -->\nbody\n")
    mdc(project, "py-style", "globs: **/*.py", "Use 4-space indent.")
    rules = core.load_rules(project)
    assert all(r.path != gen for r in rules)
    assert [r.name for r in rules].count("py-style") == 1


def test_list_globs_parsed(project):
    mdc(project, "multi", 'globs: ["src/**/*.py", "*.md"]', "body")
    (rule,) = core.load_rules(project)
    assert rule.globs == ["src/**/*.py", "*.md"]


def test_cache_invalidates_on_mtime(project):
    p = mdc(project, "r1", "globs: **/*.py", "one")
    (r1,) = core.load_rules(project)
    assert r1.body == "one"
    os.utime(p, ns=(0, 0))
    p.write_text("---\nglobs: **/*.py\n---\n\ntwo\n")
    (r2,) = core.load_rules(project)
    assert r2.body == "two"


# -- glob matching -----------------------------------------------------------


@pytest.mark.parametrize(
    "pattern,path,expected",
    [
        ("src/**/*.py", "src/app.py", True),
        ("src/**/*.py", "src/a/b/c.py", True),
        ("src/*.py", "src/a/b/c.py", False),
        ("*.py", "src/app.py", True),          # bare pattern matches basename anywhere
        ("*.md", "README.md", True),
        ("**/*.md", "docs/deep/nested.md", True),
        ("src/**", "src/a/b/c.py", True),
    ],
)
def test_glob_matching(project, pattern, path, expected):
    mdc(project, "g", f"globs: {pattern}", "body")
    (rule,) = core.load_rules(project)
    target = project / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("")
    assert core.rule_matches_path(rule, str(target), base=project) is expected


def test_rules_for_paths_dedupes(project):
    mdc(project, "py", "globs: src/**/*.py", "py rules")
    mdc(project, "all", "globs: **/*", "all rules")
    matched = core.rules_for_paths([str(project / "src" / "app.py")], base=project)
    assert {r.name for r in matched} == {"py", "all"}


# -- injection state ---------------------------------------------------------


def test_mark_injected_once_per_session(project):
    assert core.mark_injected("s1", "k") is True
    assert core.mark_injected("s1", "k") is False
    assert core.mark_injected("s2", "k") is True
    core.reset_session("s1")
    assert core.mark_injected("s1", "k") is True


# -- tool arg extraction ------------------------------------------------------


def test_candidate_paths():
    assert core.candidate_paths("read_file", {"path": "/a/b.py"}) == ["/a/b.py"]
    assert core.candidate_paths("write_file", {"file_path": "/c", "path": "/d"}) == ["/d", "/c"]
    assert core.candidate_paths("terminal", {"command": "ls", "workdir": "/w"}) == ["/w"]
    assert core.candidate_paths("terminal", {"command": "ls"}) == []
    assert core.candidate_paths("web_search", {"query": "x"}) == []


# -- middleware injection -----------------------------------------------------


def test_injection_middleware(project, monkeypatch):
    plugin = _load_plugin()
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    mdc(project, "py", "globs: src/**/*.py", "Never use wildcard imports.")

    result = plugin._on_tool_execution(
        tool_name="read_file", args={"path": str(project / "src" / "app.py")},
        session_id="s-inj", next_call=lambda a: {"output": "file content"},
    )
    assert "Never use wildcard imports." in result["output"]
    # second call in same session -> one-line reminder, no full body again
    result2 = plugin._on_tool_execution(
        tool_name="read_file", args={"path": str(project / "src" / "app.py")},
        session_id="s-inj", next_call=lambda a: "raw",
    )
    assert isinstance(result2, str)
    assert "Never use wildcard imports." not in result2
    assert "reminder" in result2
    core.reset_session("s-inj")


def test_injection_skips_non_matching(project, monkeypatch):
    plugin = _load_plugin()
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    mdc(project, "py", "globs: src/**/*.py", "Never use wildcard imports.")
    result = plugin._on_tool_execution(
        tool_name="read_file", args={"path": str(project / "README.md")},
        session_id="s-skip", next_call=lambda a: "raw",
    )
    assert result == "raw"
    core.reset_session("s-skip")


# -- enforce gates ------------------------------------------------------------


def test_enforce_pass_and_fail(project, monkeypatch):
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    mdc(project, "lint", 'globs: "*.py"\nenforce: python3 -c "import sys; sys.exit(0)"', "body")
    changed = [str(project / "src" / "app.py")]
    assert enforce.run_enforce(changed, base=project, session_id="s-enf", use_cache=False) is None

    p = project / ".cursor" / "rules" / "lint.mdc"
    p.write_text(
        '---\nglobs: "*.py"\nenforce: python3 -c "import sys; sys.stderr.write(\'boom\'); sys.exit(1)"\n---\n\nbody\n'
    )
    os.utime(p, ns=(0, 0))
    message = enforce.run_enforce(changed, base=project, session_id="s-enf2", use_cache=False)
    assert message is not None
    assert "lint" in message and "boom" in message


def test_enforce_no_match_no_run(project):
    mdc(project, "mdonly", 'globs: "*.md"\nenforce: exit 1', "body")
    assert enforce.run_enforce([str(project / "src" / "app.py")], base=project, use_cache=False) is None


def test_enforce_rule_files_env(project):
    script = project / "check.sh"
    script.write_text("#!/bin/sh\n[ -n \"$RULE_FILES\" ] && echo \"got:$RULE_FILES\" && exit 1\n")
    script.chmod(0o755)
    mdc(project, "env", f'globs: "*.py"\nenforce: {script}', "body")
    message = enforce.run_enforce([str(project / "src" / "app.py")], base=project, use_cache=False)
    assert message is not None
    assert "got:" in message


def test_enforce_without_globs_gets_all_scope(project):
    mdc(project, "nog", 'enforce: python3 -c "import sys; sys.exit(2)"', "body")
    message = enforce.run_enforce([str(project / "README.md")], base=project, use_cache=False)
    assert message is not None and "nog" in message


def test_pre_verify_hook_shape(project, monkeypatch):
    plugin = _load_plugin()
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    mdc(project, "gate", 'globs: "*.py"\nenforce: python3 -c "import sys; sys.exit(3)"', "body")
    verdict = plugin._on_pre_verify(
        session_id="s-pv", changed_paths=[str(project / "src" / "app.py")], attempt=0)
    assert verdict is not None and verdict["action"] == "continue"
    assert "gate" in verdict["message"]
    # passing gate -> None (turn may finish)
    (project / ".cursor" / "rules" / "gate.mdc").write_text(
        '---\nglobs: "*.py"\nenforce: python3 -c "import sys; sys.exit(0)"\n---\n\nbody\n')
    os.utime(project / ".cursor" / "rules" / "gate.mdc", ns=(0, 0))
    assert plugin._on_pre_verify(
        session_id="s-pv2", changed_paths=[str(project / "src" / "app.py")], attempt=0) is None


# -- sync ----------------------------------------------------------------------


def test_sync_generates_and_prunes(project):
    mdc(project, "py", "globs: src/**/*.py", "Use 4-space indent.")
    mdc(project, "db", "description: migrations", "Always rollback.")
    report = sync_rules.sync(str(project))
    created = report.split("created: ")[1].split("\n")[0] if "created: " in report else ""
    assert sorted(created.split(", ")) == ["db.md", "py.md"]

    gen = (project / ".claude" / "rules" / "py.md").read_text()
    assert "Use 4-space indent." in gen
    assert "src/**/*.py" in gen

    # generated files are not re-imported as rules
    names = [r.name for r in core.load_rules(project)]
    assert names.count("py") == 1

    # prune: remove one .mdc
    (project / ".cursor" / "rules" / "db.mdc").unlink()
    report2 = sync_rules.sync(str(project))
    assert "removed: db.md" in report2
    assert not (project / ".claude" / "rules" / "db.md").exists()


def test_sync_idempotent(project):
    mdc(project, "py", "globs: **/*.py", "Same.")
    first = sync_rules.sync(str(project))
    second = sync_rules.sync(str(project))
    assert "created" in first and "unchanged: py.md" in second


# -- prompt section --------------------------------------------------------------


def test_prompt_section_renders(project, monkeypatch):
    plugin = _load_plugin()
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    mdc(project, "house", "alwaysApply: true", "Be terse.")
    mdc(project, "db", "description: migrations", "Always rollback.")
    text = plugin._render_prompt_section({"session_id": "s", "cwd": str(project)})
    assert "Be terse." in text
    assert "db" in text and "migrations" in text
    assert "Always rollback." not in text  # desc rules stay one-line


def test_prompt_section_empty(project, monkeypatch):
    plugin = _load_plugin()
    monkeypatch.setattr(core, "session_cwd", lambda explicit=None: project)
    assert plugin._render_prompt_section({}) == ""


def test_register_uses_documented_surfaces():
    plugin = _load_plugin()
    registered = {"middleware": [], "hooks": [], "sections": [], "commands": []}

    class Ctx:
        def register_middleware(self, kind, cb):
            registered["middleware"].append(kind)

        def register_hook(self, name, cb):
            registered["hooks"].append(name)

        def register_system_prompt_section(self, sid, content, position="after_memory"):
            registered["sections"].append((sid, position))

        def register_command(self, name, handler=None, description=""):
            registered["commands"].append(name)

    plugin.register(Ctx())
    assert registered["middleware"] == ["tool_execution"]
    assert set(registered["hooks"]) == {"post_tool_call", "pre_verify"}
    assert registered["sections"] == [("context.rules.manifest", "after_memory")]
    assert registered["commands"] == ["context-rules"]
