"""zcode sync target: .zcode/rules/*.md projections + AGENTS.md digest block.

Contract (openspec/changes/sync-zcode-target):
- same projection header as the claude target (projection_content verbatim)
- .zcode/rules is NEVER a rule source (load_rules does not read it)
- digest block in <root>/AGENTS.md between BEGIN/END:RULE-DIGESTS markers;
  only lines strictly between markers are ever rewritten
- no flag = claude only, zero .zcode/AGENTS.md side effects (D3)
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != REPO.resolve()]


def _load_plugin():
    name = "context_rules_plugin"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, REPO / "__init__.py", submodule_search_locations=[str(REPO)])
    module = importlib.util.module_from_spec(spec)
    module.__package__ = name
    module.__path__ = [str(REPO)]
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_plugin = _load_plugin()
core = _plugin.core
sync_rules = _plugin.sync_rules


def mdc(tmp_path: Path, name: str, front: str, body: str) -> Path:
    p = tmp_path / ".cursor" / "rules" / f"{name}.mdc"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(f"---\n{front}\n---\n\n{body}\n")
    return p


def make_project(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir(exist_ok=True)
    (tmp_path / ".cursor" / "rules").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    return tmp_path


def three_canon_rules(project: Path) -> None:
    """glob + always + desc modes — one of each projection shape."""
    mdc(project, "py", 'globs: ["**/*.py"]', "Python body.")
    mdc(project, "team", "alwaysApply: true", "Always body.")
    mdc(project, "db", "description: DB guardrails", "Desc body.")


def test_help_mentions_target_flag():
    assert "--target" in _plugin._HELP


def test_no_flag_is_claude_only_zero_zcode_side_effects(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project))  # no target arg: pre-change behavior
    assert out.startswith("context-rules sync [claude (default)]:")
    assert not (project / ".zcode").exists()
    assert not (project / "AGENTS.md").exists()
    assert (project / ".claude" / "rules" / "py.md").exists()


def test_target_all_materializes_both_targets_with_same_header(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project), target="all")
    claude_section, zcode_section = out.split("\n\n")
    assert "claude" in claude_section and "zcode" not in claude_section
    assert zcode_section.startswith("context-rules sync [zcode]:")
    for name in ("py", "team", "db"):
        claude_proj = (project / ".claude" / "rules" / f"{name}.md").read_text()
        zcode_proj = (project / ".zcode" / "rules" / f"{name}.md").read_text()
        # same projection_content output verbatim: marked header + relpath
        assert claude_proj == zcode_proj
        head = zcode_proj.splitlines()[0]
        assert "generated by hermes context-rules" in head
        assert f"from .cursor/rules/{name}.mdc" in head
        assert "do not edit here" in head
    # mode notes survive into the projection bodies; a desc rule's projection
    # carries the apply-note (its description surfaces in the digest block)
    assert "Apply unconditionally." in (project / ".zcode" / "rules" / "team.md").read_text()
    assert "Apply when relevant." in (project / ".zcode" / "rules" / "db.md").read_text()
    assert "Desc body." in (project / ".zcode" / "rules" / "db.md").read_text()


def test_second_zcode_sync_is_a_true_noop(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    proj = project / ".zcode" / "rules" / "py.md"
    before_m = proj.stat().st_mtime_ns
    before = proj.read_bytes()
    out = sync_rules.sync(str(project), target="zcode")
    assert proj.stat().st_mtime_ns == before_m  # no rewrite
    assert proj.read_bytes() == before
    assert "unchanged: db.md, py.md, team.md" in out
    assert "created" not in out and "updated" not in out
    assert "digest: unchanged" in out


def test_zcode_alone_leaves_claude_untouched(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project), target="zcode")
    assert out.startswith("context-rules sync [zcode]:")
    assert not list((project / ".claude" / "rules").glob("*.md"))
    assert (project / ".zcode" / "rules" / "py.md").exists()


def test_load_rules_never_reads_zcode_rules(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    # a plausible rule sitting in .zcode/rules must stay invisible
    (project / ".zcode" / "rules" / "zcodething.md").write_text(
        "Handwritten-looking zcode rule body.\n")
    rules = core.load_rules(project)
    names = [r.name for r in rules]
    assert "zcodething" not in names
    assert all(".zcode" not in r.path.parts for r in rules)
    # canon rules still discovered exactly once (projection not double-counted)
    assert names.count("py") == 1


def test_all_target_runs_claude_first_then_zcode(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "py", 'globs: ["**/*.py"]', "Body.")
    out = sync_rules.sync(str(project), target="all")
    sections = out.split("\n\n")
    assert len(sections) == 2
    assert sections[0].startswith("context-rules sync [claude (default)]:")
    assert sections[1].startswith("context-rules sync [zcode]:")
    assert "created: py.md" in sections[0]
    assert "created: py.md" in sections[1]
    assert "digest: created" in sections[1]
    assert "digest" not in sections[0]
