"""zcode sync target: .zcode/rules/*.md projections + AGENTS.md digest block.

Contract (openspec/changes/sync-zcode-target):
- same projection header as the claude target (projection_content verbatim)
- .zcode/rules is NEVER a rule source (load_rules does not read it)
- digest block in <root>/AGENTS.md between BEGIN/END:RULE-DIGESTS markers;
  only lines strictly between markers are ever rewritten
- no flag = claude only, zero .zcode/AGENTS.md side effects (D3)
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path[:] = [p for p in sys.path if Path(p or ".").resolve() != REPO.resolve()]


def _load_plugin():
    name = "context_rules_plugin"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(
        name, REPO / "__init__.py", submodule_search_locations=[str(REPO)])
    module = importlib.util.module_from_spec(spec)
    module.__package__ = name
    module.__path__ = [str(REPO)]
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


_plugin = _load_plugin()
core = _plugin.core
sync_rules = _plugin.sync_rules


def mdc(tmp_path: Path, name: str, front: str, body: str) -> Path:
    p = tmp_path / ".cursor" / "rules" / f"{name}.mdc"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(f"---\n{front}\n---\n\n{body}\n")
    return p


def make_project(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir(exist_ok=True)
    (tmp_path / ".cursor" / "rules").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".claude" / "rules").mkdir(parents=True, exist_ok=True)
    return tmp_path


def three_canon_rules(project: Path) -> None:
    """glob + always + desc modes — one of each projection shape."""
    mdc(project, "py", 'globs: ["**/*.py"]', "Python body.")
    mdc(project, "team", "alwaysApply: true", "Always body.")
    mdc(project, "db", "description: DB guardrails", "Desc body.")


def test_help_mentions_target_flag():
    assert "--target" in _plugin._HELP


def test_no_flag_is_claude_only_zero_zcode_side_effects(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project))  # no target arg: pre-change behavior
    assert out.startswith("context-rules sync [claude (default)]:")
    assert not (project / ".zcode").exists()
    assert not (project / "AGENTS.md").exists()
    assert (project / ".claude" / "rules" / "py.md").exists()


def test_target_all_materializes_both_targets_with_same_header(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project), target="all")
    claude_section, zcode_section = out.split("\n\n")
    assert "claude" in claude_section and "zcode" not in claude_section
    assert zcode_section.startswith("context-rules sync [zcode]:")
    for name in ("py", "team", "db"):
        claude_proj = (project / ".claude" / "rules" / f"{name}.md").read_text()
        zcode_proj = (project / ".zcode" / "rules" / f"{name}.md").read_text()
        # same projection_content output verbatim: marked header + relpath
        assert claude_proj == zcode_proj
        head = zcode_proj.splitlines()[0]
        assert "generated by hermes context-rules" in head
        assert f"from .cursor/rules/{name}.mdc" in head
        assert "do not edit here" in head
    # mode notes survive into the projection bodies; a desc rule's projection
    # carries the apply-note (its description surfaces in the digest block)
    assert "Apply unconditionally." in (project / ".zcode" / "rules" / "team.md").read_text()
    assert "Apply when relevant." in (project / ".zcode" / "rules" / "db.md").read_text()
    assert "Desc body." in (project / ".zcode" / "rules" / "db.md").read_text()


def test_second_zcode_sync_is_a_true_noop(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    proj = project / ".zcode" / "rules" / "py.md"
    before_m = proj.stat().st_mtime_ns
    before = proj.read_bytes()
    out = sync_rules.sync(str(project), target="zcode")
    assert proj.stat().st_mtime_ns == before_m  # no rewrite
    assert proj.read_bytes() == before
    assert "unchanged: db.md, py.md, team.md" in out
    assert "created" not in out and "updated" not in out
    assert "digest: unchanged" in out


def test_zcode_alone_leaves_claude_untouched(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project), target="zcode")
    assert out.startswith("context-rules sync [zcode]:")
    assert not list((project / ".claude" / "rules").glob("*.md"))
    assert (project / ".zcode" / "rules" / "py.md").exists()


def test_load_rules_never_reads_zcode_rules(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    # a plausible rule sitting in .zcode/rules must stay invisible
    (project / ".zcode" / "rules" / "zcodething.md").write_text(
        "Handwritten-looking zcode rule body.\n")
    rules = core.load_rules(project)
    names = [r.name for r in rules]
    assert "zcodething" not in names
    assert all(".zcode" not in r.path.parts for r in rules)
    # canon rules still discovered exactly once (projection not double-counted)
    assert names.count("py") == 1


def test_all_target_runs_claude_first_then_zcode(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "py", 'globs: ["**/*.py"]', "Body.")
    out = sync_rules.sync(str(project), target="all")
    sections = out.split("\n\n")
    assert len(sections) == 2
    assert sections[0].startswith("context-rules sync [claude (default)]:")
    assert sections[1].startswith("context-rules sync [zcode]:")
    assert "created: py.md" in sections[0]
    assert "created: py.md" in sections[1]
    assert "digest: created" in sections[1]
    assert "digest" not in sections[0]


# ---------------------------------------------------------------------------
# digest block in AGENTS.md (task 4.2)


def agents(project: Path) -> Path:
    return project / "AGENTS.md"


def digest_lines_of(text: str) -> list:
    begin = text.index(sync_rules.DIGEST_BEGIN)
    end = text.index(sync_rules.DIGEST_END)
    return [ln for ln in text[begin + len(sync_rules.DIGEST_BEGIN):end].splitlines() if ln.strip()]


def test_digest_created_in_missing_agents_md(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    out = sync_rules.sync(str(project), target="zcode")
    text = agents(project).read_text()
    assert text.startswith("# Project rules\n\n<!-- BEGIN:RULE-DIGESTS -->\n")
    assert text.endswith("<!-- END:RULE-DIGESTS -->\n")
    # one line per rule, sorted by name, description preferred over note
    assert digest_lines_of(text) == [
        "- **db** — DB guardrails",
        "- **py** — Apply when working with files matching: **/*.py.",
        "- **team** — Apply unconditionally.",
    ]
    assert "digest: created" in out


def test_digest_preserves_handwritten_paragraphs_byte_for_byte(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    before_text = (
        "# Workspace notes\n\nHandwritten intro paragraph.\n\n"
        "<!-- BEGIN:RULE-DIGESTS -->\nstale line\n<!-- END:RULE-DIGESTS -->\n\n"
        "Handwritten outro, must survive.\n"
    )
    agents(project).write_text(before_text)
    out1 = sync_rules.sync(str(project), target="zcode")
    after1 = agents(project).read_text()
    assert "- **db** — DB guardrails" in after1
    assert "stale line" not in after1
    assert "digest: updated" in out1
    # second sync: idempotent, paragraphs still byte-identical
    out2 = sync_rules.sync(str(project), target="zcode")
    after2 = agents(project).read_text()
    assert after1 == after2
    assert "digest: unchanged" in out2
    # only the marked block moved; the prose is untouched
    assert after1.startswith("# Workspace notes\n\nHandwritten intro paragraph.\n\n")
    assert after1.endswith("Handwritten outro, must survive.\n")


def test_digest_line_dropped_when_canon_deleted(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    (project / ".cursor" / "rules" / "db.mdc").unlink()
    out = sync_rules.sync(str(project), target="zcode")
    text = agents(project).read_text()
    lines = digest_lines_of(text)
    assert len(lines) == 2
    assert "db" not in " ".join(lines)
    assert "digest: updated" in out


def test_single_marker_file_is_skipped_untouched(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    malformed = (
        "# Notes\n\n<!-- BEGIN:RULE-DIGESTS -->\noperator content here\n"
    )
    agents(project).write_text(malformed)
    before_bytes = agents(project).read_bytes()
    before_m = agents(project).stat().st_mtime_ns
    out = sync_rules.sync(str(project), target="zcode")
    assert agents(project).read_bytes() == before_bytes
    assert agents(project).stat().st_mtime_ns == before_m
    assert "digest: skipped" in out
    assert "not auto-repaired" in out


def test_zero_rules_clears_lines_keeps_markers(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    for f in (project / ".cursor" / "rules").glob("*.mdc"):
        f.unlink()
    out = sync_rules.sync(str(project), target="zcode")
    text = agents(project).read_text()
    assert digest_lines_of(text) == []
    assert sync_rules.DIGEST_BEGIN in text and sync_rules.DIGEST_END in text
    assert "digest: cleared" in out


def test_unknown_target_usage_error_writes_nothing(tmp_path, monkeypatch):
    project = make_project(tmp_path)
    three_canon_rules(project)
    monkeypatch.setattr(sync_rules, "session_cwd", lambda explicit=None: project)
    # direct plugin invocation, exactly how the slash command dispatches
    out = _plugin._handle_slash("sync --target vim")
    assert "usage" in out.lower()
    assert "claude" in out and "zcode" in out and "all" in out
    assert not (project / ".zcode").exists()
    assert not (project / "AGENTS.md").exists()
    assert not list((project / ".claude" / "rules").glob("*.md"))


def test_target_form_equivalent_and_rejected_tokens(tmp_path, monkeypatch):
    project = make_project(tmp_path)
    three_canon_rules(project)
    monkeypatch.setattr(sync_rules, "session_cwd", lambda explicit=None: project)
    out = _plugin._handle_slash("sync --target=zcode")
    assert "context-rules sync [zcode]: " in out
    assert (project / ".zcode" / "rules" / "py.md").exists()
    # a bare unknown token is a usage error too
    out2 = _plugin._handle_slash("sync now")
    assert "usage" in out2.lower()


# ---------------------------------------------------------------------------
# stale cleanup + handwritten-file safety in .zcode/rules (task 4.3)


def test_orphaned_zcode_projection_pruned_and_digest_line_dropped(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    (project / ".cursor" / "rules" / "db.mdc").unlink()
    out = sync_rules.sync(str(project), target="zcode")
    assert not (project / ".zcode" / "rules" / "db.md").exists()
    assert "removed: db.md" in out
    assert "db" not in " ".join(digest_lines_of(agents(project).read_text()))


def test_unparsable_ref_projection_pruned_by_stem_in_zcode(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    sync_rules.sync(str(project), target="zcode")
    # stale projection whose header reference is corrupted (unparsable) is
    # pruned by the canon-stem rule once the same-stem .mdc is gone —
    # exactly like the claude target
    proj = project / ".zcode" / "rules" / "db.md"
    proj.write_text(
        "<!-- generated by hermes context-rules from ??corrupted?? -->\n\nBody.\n")
    (project / ".cursor" / "rules" / "db.mdc").unlink()
    out = sync_rules.sync(str(project), target="zcode")
    assert not proj.exists()
    assert "removed: db.md" in out


def test_unparseable_canon_keeps_its_zcode_projection(tmp_path):
    project = make_project(tmp_path)
    mdc(project, "py", 'globs: ["**/*.py"]', "Body.")
    sync_rules.sync(str(project), target="zcode")
    # canon still exists but became unreadable: existence check, not parse
    (project / ".cursor" / "rules" / "py.mdc").write_bytes(b"\xff\xfe\x00bad")
    sync_rules.sync(str(project), target="zcode")
    assert (project / ".zcode" / "rules" / "py.md").exists()


def test_handwritten_zcode_file_never_touched_collides_as_skipped(tmp_path):
    project = make_project(tmp_path)
    three_canon_rules(project)
    keep = project / ".zcode" / "rules" / "py.md"
    keep.parent.mkdir(parents=True, exist_ok=True)
    keep.write_text("Handwritten zcode note.\n")
    out = sync_rules.sync(str(project), target="zcode")
    assert keep.read_text() == "Handwritten zcode note.\n"  # byte-identical
    assert "skipped" in out and "handwritten" in out
    # the canon rule of the same name gets no digest line (not materialized)
    assert "- **py**" not in agents(project).read_text()


def test_zcode_duplicate_prune_keeps_only_when_managed_written(tmp_path):
    """A marked pre-rename projection stays the canon's only projection when
    the managed name is occupied by a handwritten file — mirrors claude."""
    project = make_project(tmp_path)
    mdc(project, "style", 'globs: ["**/*.py"]', "Body.")
    (project / ".zcode" / "rules").mkdir(parents=True, exist_ok=True)
    (project / ".zcode" / "rules" / "python-style.md").write_text("Handwritten note.\n")
    # a stale marked projection referencing a RENAMED-AWAY canon (style.mdc
    # no longer exists; python-style.mdc does): its ref parses, canon gone,
    # BUT the managed name is handwritten-occupied and was never written,
    # so this projection is the canon's only projection and must be kept
    (project / ".zcode" / "rules" / "style.md").write_text(
        "<!-- generated by hermes context-rules from .cursor/rules/style.mdc — do not edit here; edit the .mdc. -->\n\nBody.\n")
    mdc(project, "python-style", 'globs: ["**/*.py"]', "New body.")
    out = sync_rules.sync(str(project), target="zcode")
    assert (project / ".zcode" / "rules" / "style.md").exists()  # kept: canon's only projection
    assert (project / ".zcode" / "rules" / "python-style.md").read_text() == "Handwritten note.\n"
    assert "skipped" in out
